---
- name: int service deploymnent
  hosts: intservice
  become: yes


  tasks:
    - name: Make sure docker is installed
      apt:
        name: docker
        state: present
        update_cache: yes


    - name: Start docker service
      service:
        name: docker
        state: started


